# Generated by Django 4.1.2 on 2022-10-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0002_delete_teacherlogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_email', models.CharField(max_length=30)),
                ('teacher_password', models.CharField(max_length=20)),
            ],
        ),
    ]
